services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=project'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD='
      - 'MYSQL_USER='
    ports:
      - '3306'
